### PR TITLE
Added 2013 Support!

### PR DESCRIPTION
**Pull request by owen2**
Updated the project and manifest files.

### CODE REVIEW

**Comment by lukesdm** [comment]
Hi Owen, thanks for this. I will be free to take a look at the end of next week.

**Comment by dmalikov** [comment]
@lukesdm what is the status of this enhancement?

**Comment by owen2** [comment]
I only had to migrate the .csproj and add to the manifest. I didn't actually change any of the code.

**Comment by lukesdm** [comment]
Hi, @owen2 is this working in VS2012 for you? On my machine, it works in 2013 but not 2012. I am tempted to update the readme on the front page of this repo to point to your fork for 2013 support. I don't use the extension myself any more as it interferes with some other extensions.

**Comment by owen2** [comment]
The extension can be installed on 2012, but you have to use 2013 to compile it. 

-----Original Message-----

**Comment by lukesdm** [comment]
Looks like this is now a feature in the VS 2013 Productivity Power Tools. I recommend switching to that - it probably plays nicer with other installed extensions. http://blogs.msdn.com/b/visualstudio/archive/2014/05/23/announcing-update-to-productivity-power-tools-2013.aspx

**Comment by owen2** [comment]
sounds good to me. I updated my readme to reflect this.

**Pull request closed without merging**
